

```python
# def show(self):
#     for ch in self.bar:
#         print(ch,sep=' ',end=' ')
#     print(' ',end='\r')
```


```python
## f.close()
```


```python
## f=open('test.txt','w')
```


```python
## f.write('hello')
```


```python
# f.close()
# f=open('test.txt')
# f.read()
# f.tell()
# f.seek(5)
# f.close()

## 注意就是要进行下一步处理前，要把之前的文档关闭，不然就会不能打开
```


```python
# lines=['hello\n','word\n','test\n']
# f=open('test.txt','w')
# f.writelines(lines)
# f.close()

# # 疑问：这个txt文档是建立在哪里？
```


```python
##  因为close函数大部分人都会忘掉写，所以就用with代替，用with的话，进入with函数就会打开这个文件，如果退出with这一块的话，就会自动调用close函数，就会自动关闭
#  with open('test.txt') as f:
#     print(f.read())
```


```python
# import fileinput
# for line in fileinput.input(inplace=True):
#     line=line.rstrip()
#     num=fileinput.lineno()
#     print({'{:<50} # {:2d}'.format(line,num)})
```


    ---------------------------------------------------------------------------

    FileNotFoundError                         Traceback (most recent call last)

    <ipython-input-11-415f4562ed0e> in <module>
          1 import fileinput
    ----> 2 for line in fileinput.input(inplace=True):
          3     line=line.rstrip()
          4     num=fileinput.lineno()
          5     print({'{:<50} # {:2d}'.format(line,num)})
    

    C:\study\anzuang\lib\fileinput.py in __next__(self)
        250     def __next__(self):
        251         while True:
    --> 252             line = self._readline()
        253             if line:
        254                 self._filelineno += 1
    

    C:\study\anzuang\lib\fileinput.py in _readline(self)
        337                     pass
        338                 # The next few lines may raise OSError
    --> 339                 os.rename(self._filename, self._backupfilename)
        340                 self._file = open(self._backupfilename, self._mode)
        341                 try:
    

    FileNotFoundError: [WinError 2] 系统找不到指定的文件。: '-f' -> '-f.bak'



```python
##  with使用的案例
# def process_line(line):
#     print('prcessing:{}'.format(line))
    
# with open('test.txt') as f:
#     while Ture:
#         line=f.readline() #read(i)--char by char
#         if not line:break
#         process_line(line)
```


```python
#  该案例为设置一个窗口，和之前的计算器类似

from tkinter import *
from tkinter import ttk
from tkinter.scrolledtext import Scrolledtext

class SimpleEditor(Tk):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.setup_ui()
        
    def setup_ui(self):
        self.title('Simple editing')
        self.contents=ScrolledText()
        self.contents.pack(side=BOTTON,expand=True,fill=BOTH) 
    
        self.file_name=StringVar()
        self.filename=ttk,Entry(textvariable=self.file_name)
        self.filename.pack(side=LEFT,expand=True,fill=x)
        self.file_name.set('romo.txt')
     
        ttk.Button(text='load',command=self.load).pack(side=LEFT)
        ttk.Button(text='save',command=self.save).pack(side=LEFT)
        self.add_line_number=BooleanVar()
        ttk.Checkbutton(text='Line number',command=self.add_line_number,
                       variable=self.add_line_number).pack(side=LEFT)
       
    def load(self):
        with open(self.file_name.get(),encoding='UTF-8')as files:
            self.contents.delete('1.0',END)
            if self.add_line_number.get():
                line_number=1
                for line in file:
                    self.contents.insert(INSERT,'{}\t'.format(line_number)+line)
                    line_number+=1
            else:
                self.contents.insert(INSRET，file.read())
    
    def save(self):
        with open(self.file_name.get(),'w',,encoding='UTF-8')as files:
            file.write(self.contents.get('1.0'),END)
            
    def on_add_line_number(self,*args):
        lines=self.contents.get('1.0',END)
        with open()
        

SimpleEditor().mainloop()


##不知道为什么一直报“self.contents.insert(INSRET，file.read())”的错误？？？
        
```


      File "<ipython-input-29-0a213f686567>", line 37
        self.contents.insert(INSRET，file.read())
                                       ^
    SyntaxError: invalid character in identifier
    



```python
# with open('remeo.txt',encoding='UTF-8') as f:
#     for line in f.readlines():
#         print(line)
```


    ---------------------------------------------------------------------------

    FileNotFoundError                         Traceback (most recent call last)

    <ipython-input-19-ec10c7d308f7> in <module>
    ----> 1 with open('remeo.txt',encoding='UTF-8') as f:
          2     for line in f.readlines():
          3         print(line)
    

    FileNotFoundError: [Errno 2] No such file or directory: 'remeo.txt'



```python
## 简单的数据库，使用较方便

import shelve

s=shelve.open('my_shelve')
s['entry1']=[1,2,3]
s['entry2']=['hello']

```


```python
test=s['entry1']
test.append(4)
s['entry1']

##会发现4并没有加进数据库
```




    [1, 2, 3]




```python
test=s['entry1']
test.append(4)
s['entry1']=test
s['entry1']

##只能对数据库重新赋值
```




    [1, 2, 3, 4]




```python
import json
json.__all__
```




    ['dump',
     'dumps',
     'load',
     'loads',
     'JSONDecoder',
     'JSONDecodeError',
     'JSONEncoder']




```python
my_list=[1,2,3,4]
with open('output.json','w')as f:
    json.dump(my_list,f)
    
##存为output.json名称的文件
```


```python
with open('output.json','r')as f:
    my_list=json.load(f)
```


```python
my_list
```




    [1, 2, 3, 4]




```python

```
